version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - secretbay_data:/app/data
    restart: unless-stopped
    environment:
      - PORT=8080
      - LOG_LEVEL=info
      - TEMP_DIR=/app/data/temp
      - JWT_SECRET=${JWT_SECRET:-change-me-in-production}
    networks:
      - secretbay-network

  # Frontend service could be added here when developed
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - secretbay-network

volumes:
  secretbay_data:
    driver: local

networks:
  secretbay-network:
    driver: bridge 